### ISSUE TITLE
Position and/or className support

### ISSUE THREAD

**Issue by austinmayer** [RenaudRohlinger/r3f-perf#2]
Fantastic lib, thanks for formalizing this into a new standard package for r3f.

Using this with other dev tool libraries such as https://github.com/pmndrs/use-tweaks causes UI collisions as they are both positioned in the top right. Thoughts on adding support for position (top, right, bottom, left) and/or className support on `<Perf />` so manual CSS overrides are possible?

**Comment by RenaudRohlinger** [comment]
Oh that's a good idea. Best option would be able to easily extend the className I guess. I will work on that tomorrow 👍

**Comment by RenaudRohlinger** [comment]
@austinmayer You can now override the className with v0.76.0

**Comment by austinmayer** [comment]
Tested and working great, thanks!
