### ISSUE TITLE
Toggle Button covers panel

### ISSUE THREAD

**Issue by marcelmusiol** [RenaudRohlinger/r3f-perf#20]
Just a small issue and probably an easy fix: The toggle button covers the panel and in the "bottom-right" position it makes it difficult to read the value for the triangles.
<img width="335" alt="Screen Shot 2021-06-03 at 2 22 16 PM" src="https://user-images.githubusercontent.com/46103209/120644162-51f38c00-c477-11eb-9f9b-0f51ae2a993a.png">
<img width="335" alt="Screen Shot 2021-06-03 at 2 22 39 PM" src="https://user-images.githubusercontent.com/46103209/120644165-528c2280-c477-11eb-80ff-9379d4118abd.png">

Edit: I just noticed this might be a Problem with Chakra UI since this issue only appears when using Chakra UI. I believe Chakra UI uses some global CSS resets. Maybe that's what's causing it.

**Comment by RenaudRohlinger** [comment]
@marcelmusiol Thanks for the feedback. I will implement a basic CSS reset on the container of the module it might fix that issue!

**Comment by marcelmusiol** [comment]
Thanks! And thank you for providing this tool! Especially when learning three js and react three fiber I find it very helpful as you can immediately tell if some code is not performing well.

**Comment by RenaudRohlinger** [comment]
@marcelmusiol Version 3.2.0 release should fix that issue. Also improved the chart settings and fixed the trackGPU parameter. Thank you for the kind words it motivates me to keep working on these kind of tools :relaxed:
