### ISSUE TITLE
No Graph/Chart when disabling/re-enabling component

### ISSUE THREAD

**Issue by JackDapid** [RenaudRohlinger/r3f-perf#23]
When disabling (not rendering) component and re-enabling it, the graphs/charts are not shown anymore.
Two different methods tried:

`{perf_toggle ? <Perf position={perf_pos} /> : null}`
or
 `<Perf headless={perf_toggle} position={perf_pos} />`

both with same result: Graph/Chart not show the component activated second time:
e.g. using here 2nd example

1. perf_toggle = true => perf GUI not shown (as expected)
2. perf_toggle = false => perf GUI shown with Graph (as expected)
![Screenshot 2021-10-29 at 06 06 51](https://user-images.githubusercontent.com/8346230/139374219-5fe6aa3f-6640-4ba0-8a8a-af1b80c34dbf.png)

3. perf_toggle = true => perf GUI not shown (as expected)
4. perf_toggle = false => perf GUI shown WITHOUT Graph
![Screenshot 2021-10-29 at 06 08 53](https://user-images.githubusercontent.com/8346230/139374228-631a8219-61ff-401a-98ff-73a43bf12078.png)

**Comment by RenaudRohlinger** [comment]
Fixed with v5.2.0
