### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'count')

### ISSUE THREAD

**Issue by agcty** [RenaudRohlinger/r3f-perf#24]
whenever I use the <Perf/> component this error is thrown

![image](https://user-images.githubusercontent.com/12101091/149590941-72f22c17-fd54-496e-a8a8-4290a08d6646.png)

**Comment by RenaudRohlinger** [comment]
Ah yes, this repo is deprecated at this moment. I will do a v2 once react three fiber release the v8.

In the meantime, you could use this minimal but efficient monitor system: https://codesandbox.io/s/debug-fps-gi79o
