### ISSUE TITLE
React 18 support

### ISSUE THREAD

**Issue by gregdingle** [RenaudRohlinger/r3f-perf#25]
I'd like to use r3f-perf with the nearly released React 18. When I do, I get the warning

```
Warning: ReactDOM.render is no longer supported in React 18. Use createRoot instead. Until you switch to the new API, your app will behave as if it's running React 17. Learn more: https://reactjs.org/link/switch-to-createroot
```

**Comment by gregdingle** [comment]
The problem seems to be this line https://github.com/utsuboco/r3f-perf/blob/6711a58a97fb4612457ecf548a0fdefccd6ce674/packages/r3f-perf/src/html.tsx#L65 .

**Comment by RenaudRohlinger** [comment]
Since React 18 is still in RC and R3F is still in v7 let's wait for r3f to go v8 to use createRoot.
In the meantime, a patch would be easily possible depending on the version of React.

**Comment by gregdingle** [comment]
Sounds good. We've already patched our version of r3f-perf. 

We could also submit a PR that is backwards compatible.

**Comment by RenaudRohlinger** [comment]
Oh, that would be awesome if you could PR patch.

**Comment by RenaudRohlinger** [comment]
updated r3f-perf@6.0.0 to v18 and r3f v8

**Comment by gregdingle** [comment]
Awesome!

**Comment by DennisSmolek** [comment]
Im still having this error with 6.0.1
