### ISSUE TITLE
Excessive bundle size

### ISSUE THREAD

**Issue by gregdingle** [RenaudRohlinger/r3f-perf#26]
Hi, we love your tool. However, it depends on `react-icons` which adds >6mb to our bundle size. We had to lazy load `<Perf>` as a result. Maybe that's something you should write about in the docs?

**Comment by gregdingle** [comment]
Nevermind, [bundlephobia](https://bundlephobia.com/package/react-icons@4.3.1) shows only a few K.

**Comment by gregdingle** [comment]
I found the problem is due to tree [shaking failing](https://github.com/react-icons/react-icons/issues/154#issuecomment-818373424) for `react-icons`. The fallback solution is to use `react-icons/all-files`... or maybe just install the icon libs needed within the catch-all `react-icons`.

**Comment by gregdingle** [comment]
See https://bundlephobia.com/package/@react-icons/all-files@4.1.0

**Comment by RenaudRohlinger** [comment]
Hello!

Fixed in 5.2.0. I'm now using radix icons. See:
https://twitter.com/onirenaud/status/1495407672581300225
