### ISSUE TITLE
'FramebufferTexture' is not exported from 'three'

### ISSUE THREAD

**Issue by ashleymvanduzer** [RenaudRohlinger/r3f-perf#27]
Awesome package! Just a heads up, when trying to use the component, I get the error:

./node_modules/three-stdlib/objects/Lensflare.js
Attempted import error: 'FramebufferTexture' is not exported from 'three'.

**Comment by RenaudRohlinger** [comment]
Thanks! Fixed in 5.2.0. See:
https://twitter.com/onirenaud/status/1495407672581300225

Changelog will follow
