### ISSUE TITLE
[bug] Cannot render correctly with Z-up

### ISSUE THREAD

**Issue by HarikalarKutusu** [RenaudRohlinger/r3f-perf#30]
I have the following setting in my user-interactive application:

```
Object3D.DefaultUp.set(0, 0, 1);
```

This prevents correct rendering of r3f-perf panel.
![image](https://user-images.githubusercontent.com/8849617/156917510-ff357e81-926b-41ad-86a3-4a0053c5e928.png)

**Comment by hug-0** [comment]
Any straight forward ways to address this? I would love to be able to use this component out of the box! I could go the headless route and build my own component to render the stats, but seems like such a waste for an otherwise great plugin!

**Comment by amritbanerjee** [comment]
Was anyone able to solve this? Any easy fixes?

**Comment by sashankaryal** [comment]
Having the same issue

**Comment by Archimagus** [comment]
Same issue here.

**Comment by quirm** [comment]
The same issue, this https://github.com/utsuboco/r3f-perf/pull/51 seems as a viable fix

**Comment by RenaudRohlinger** [comment]
Solved thanks to @quirm 🙌
