### ISSUE TITLE
Consider allowing r3f-perf to be used for production environments.

### ISSUE THREAD

**Issue by simonghales** [RenaudRohlinger/r3f-perf#5]
Hey there, love the package, thanks for making it!

I was wondering if you'd consider removing the code that ensures that r3f-perf can only be used for the `development` environment.

I think it'd make more sense to allow the user to determine within their own app under what conditions they want to include the component.

Right now I wanted to check the frame rate for a build / production version of my game, but I've had to fork the repo in order to do so.

Cheers!

**Comment by RenaudRohlinger** [comment]
Hello @simonghales !

You can simply do that if you also want to use this package in production :

```jsx
import { Perf } from 'r3f-perf/dist/r3f-perf.cjs.development.js'
```

I will add it to the documentation, thanks for the feedback.

**Comment by simonghales** [comment]
Great, thank you!
